site_name: Hamza Khawar
# site_url: https://hamzakhawar.com
nav:
  - Home: index.md
  - About: about.md
  - Blog: blog.md
theme:
  name: material
  favicon: assets/images/favicon.png
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode