site_name: Hamza Khawar
site_url: https://www.hamzakhawar.com
site_author: Hamza Khawar
nav:
  - Home: index.md
  - About: about.md
  - Writing:
    - blog/index.md
  - AI Roadmap: roadmap.md
theme:
  name: material
  features:
    - navigation.indexes  
    - navigation.top
  favicon: assets/images/favicon.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
# extra_css:
  # - stylesheets/extra.css

markdown_extensions: # pictures
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra:  
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hamza-k93
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mhk02/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/hamzak.93/      
 

plugins:
  # - glightbox
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - blog:
      # categories_allowed:
      #   - General
      #   - Work
      #   - News
      pagination_per_page: 5
  - tags:
      tags_file: blog/tags.md    
  
# Copyright
copyright: Copyright &copy; 2024 - Present





# mkdocs gh-deploy --force        